### ISSUE TITLE
Mariadb does not start

### ISSUE THREAD

**Issue by boydenus** [bitnami/bitnami-docker-jasperreports#65] opened 2019-08-30 13:54 UTC
**Issue:** 
MariaDB container does not start. Ran docker container ls and only the jasperreports container shows as running. Attempting to access the host server at http://_hostname_/jasperserver results in page not found error (also tried by IP address). New Ubuntu host on VMware ESXi, followed Bitnami documentation for docker, docker-compose, and jasperreports docker install on Ubuntu 18.04.

**Host O/S and Version:** Ubuntu 18.04.3 LTS
**Docker Version:** 19.03.1
**docker info Output:**
```
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 1
  Paused: 0
  Stopped: 1
 Images: 2
 Server Version: 19.03.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-58-generic
 Operating System: Ubuntu 18.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.696GiB
 Name: boydenus-jasper
 ID: H7OE:LYW2:AMBA:SHPK:ZDKE:XLPQ:GPWY:HNOL:ZBPV:LUR7:SQR5:RFHS
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
**Command to run containers:** 
```
docker-compose up -d (from /home/trboyden where docker-compose.yml file is)
```
**docker-compose.yml contents:**
```yaml
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.3'
    environment:
      - MARIADB_USER=bn_jasperreports
      - MARIADB_DATABASE=bitnami_jasperreports
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - '/home/trboyden/bitnami/mariadb:/bitnami'
  jasperreports:
    image: 'bitnami/jasperreports:7'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - JASPERREPORTS_DATABASE_USER=bn_jasperreports
      - JASPERREPORTS_DATABASE_NAME=bitnami_jasperreports
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - '/home/trboyden/bitnami/jasper:/bitnami'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  jasperreports_data:
    driver: local
```
**docker container ls output:**
```
CONTAINER ID
e20ec5658d0e

IMAGE
bitnami/jasperreports:7

COMMAND
"/app-entrypoint.sh …"

CREATED
About an hour ago

STATUS
Up 2 minutes

PORTS
0.0.0.0:80->8080/tcp, 0.0.0.0:443->8443/tcp

NAMES
trboyden_jasperreports_1
```

**Comment by carrodher** [comment] 2019-09-02 09:01
Hi, I am not able to reproduce the issue. I used your `docker-compose.yml` but replacing the volume path and MariaDB is up and running:
```bash
$ docker ps
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                                         NAMES
6e16aba922b3        bitnami/jasperreports:7   "/app-entrypoint.sh …"   2 minutes ago       Up 2 minutes        0.0.0.0:80->8080/tcp, 0.0.0.0:443->8443/tcp   bitnamidockerkafka_jasperreports_1
824295885c0f        bitnami/mariadb:10.3      "/entrypoint.sh /run…"   2 minutes ago       Up 2 minutes        3306/tcp                                      bitnamidockerkafka_mariadb_1
```

Can you share with us the output of the initialization?

**Comment by boydenus** [comment] 2019-09-02 10:18
Where would I find that info? Thanks.

**Comment by carrodher** [comment] 2019-09-02 14:02
You can do it by running `docker-compose up` without the `-d` flag and you will see the output directly in the terminal. You can copy/paste this output here

**Comment by boydenus** [comment] 2019-09-08 12:17
Sorry for the delay on getting back to this. I ended up installing Jasper Reports manually on another server. I did want to complete the troubleshooting for this so I built another server to test this process with. 

Looks like the issue comes up when I get to the Persistence part of the instructions. If I follow the instructions and do everything as the root user, everything works as documented. However, if I follow the instructions using my normal user account and sudo, I get a permission denied error on the /bitnami/mariadb directory when the container goes to start up. This is after creating a folder (as my normal user account) named mariadb and setting the docker-compose.yml to point to it. 

So looks like there is a permission setting step missing from the instructions. Doing the same steps for the Jasper Reports container did not exhibit the same permissions error during startup. What do the permissions need to be for the "/home/${USER}/jasperreports/mariadb" directory that I created and pointed to in the docker-compose.yml file?

**Comment by boydenus** [comment] 2019-09-08 12:30
I also just tried the process again and tried putting the persistence folders in /opt/jasperreports and experienced the same permissions denied issue for mariadb. So it seems like mariadb needs extra permissions for its persistence folder that Jasper Reports does not need for its persistence folder.

**Comment by carrodher** [comment] 2019-09-10 07:33
MariaDB image is a [non-root image](https://docs.bitnami.com/containers/how-to/work-with-non-root-containers/), you can see the directive [`USER 1001`](https://github.com/bitnami/bitnami-docker-mariadb/blob/master/10.3/debian-9/Dockerfile#L24) in the Dockerfile.

Using non-root containers provide different advantages as listed in the above link, but also some side effects. One of the disadvantages is due to Docker mounts host volumes preserving the host UUID and GUID. This can lead to permission conflicts with non-root containers, as the user running the container may not have the appropriate privileges to write to the host volume.

To solve it you can provide correct permissions to your local directory you're using as the mount point and those permissions are transferred to the container. To check your specific case, can you share the permissions for your mounted folder (in your local machine)?

**Comment by boydenus** [comment] 2019-09-10 10:53
For /opt/jasperreports/mariadb the permissions are:

drwxr-xr-x 2 root root 4096 Sep  8 12:24 .
drwxr-xr-x 4 root root 4096 Sep  8 12:25 ..

For /home/trboyden/jasperreports/mariadb the permissions were:

drwxrwxr-x 2 trboyden trboyden 4096 Sep  8 12:03 .
drwxrwxr-x 4 trboyden trboyden 4096 Sep  8 12:24 ..

The user id for root is 0 (duh I guess). The user id for trboyden is 1000.

What would I change in the docker-compose.yml file to use either 0 or 1000? What is the best practice for running docker containers - under root or as a non-root user? I assumed non-root user based on the instructions, but maybe it is root based on what works out-of-the-box?

**Comment by carrodher** [comment] 2019-09-11 06:48
That is the point, the non-root user is `1001`, but this user belongs to the _root_ group and that is the key. According to your message, this is not fulfilled in any of the previous directories.

- _/opt/jasperreports/mariadb_ has the proper owner (`root:root`) but the `root` group doesn't have write permissions, so user `1001` is not able to write in this directory. You can fix it by running `sudo chmod -R g+w /opt/jasperreports/mariadb`
- _/home/trboyden/jasperreports/mariadb_ has configured properly the permissions (it is writable both, for user and group), but the group is `trboyden` and the `1001` user is not part of this group. In this case, you should be able to fix it by changing the owner group of this directory by running `sudo chown -R :root /home/trboyden/jasperreports/mariadb`

Non-root images add an extra layer of security and are generally recommended for production environments, but there are some concerns mainly because it is not possible to execute privileged tasks such as installing system packages, editing configuration files, creating system users and groups.

**Comment by boydenus** [comment] 2019-09-11 19:41
Great, that worked (I used /opt/jasperreports as that seemed more appropriate)! So I guess the only thing I'd suggest is maybe updating the documentation to verify the permissions are set correctly for mariadb. Other than that, they were great. Thanks again for your assistance.

**Comment by carrodher** [comment] 2019-09-16 07:21
We are glad that you were able to fix the issue. I'll close the issue as solved, if you have any other questions, please do not hesitate to let us know.

About documenting it, I agree, I will create an internal task to add this information to the README.

**Closed by carrodher** 2019-09-16 07:21 UTC
