### ISSUE TITLE
Image for RPI 4B 64 bit - aarch64 ?

### ISSUE THREAD

**Issue by manju-rn** [bitnami/bitnami-docker-jasperreports#113] opened 2022-01-26 04:39 UTC
Is there an image to run jasper reports in RPI 4B for 64bit rpios, specifically aarch64 ?

This would help speed up the development

**Comment by juan131** [comment] 2022-01-26 07:21
Duplicate of https://github.com/bitnami/charts/issues/7305

**Closed by juan131** 2022-01-26 07:21 UTC
